@elastic_host = http://127.0.0.1:9200
@apikey = 

###

# 列出所有 index

GET {{elastic_host}}/_cat/indices?v HTTP/1.1
Authorization: ApiKey {{apikey}}

###

# 建立 index

PUT {{elastic_host}}/my-text-202208 HTTP/1.1
Authorization: ApiKey {{apikey}}
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "message": { "type": "text" }
    }
  }
}

###

# 列出該 index 底下的資料筆數

GET {{elastic_host}}/product/_count HTTP/1.1
Authorization: ApiKey {{apikey}}

###

# 列出該 index 底下的資訊

GET {{elastic_host}}/product/_settings?pretty HTTP/1.1
Authorization: ApiKey {{apikey}}

###

# 搜尋

GET {{elastic_host}}/my-text-202208/_search HTTP/1.1
Authorization: ApiKey {{apikey}}
Content-Type: application/json

{
  "query": {
    "match_phrase": {
      "message": "Hello world"
    }
  }
}

###

# add document

POST {{elastic_host}}/my-text-202208/_doc HTTP/1.1
Authorization: ApiKey {{apikey}}
Content-Type: application/json

{
  "message": "world"
}